import { Button, ScrollView } from "std-widgets.slint";
import { Settings, SettingsPage } from "settings.slint";
import { HomePage, GameForDisplay } from "home.slint";
import { AddGamePage, Game } from "add-game.slint";

export component App inherits Window {
    in-out property <int> current_page: 0;
    in-out property <Settings> settings;
    in-out property <Game> game;
    in property <[Game]> games;
    in property <int> editing: -1;

    // home callbacks
    callback settings-clicked();
    callback add-fab-clicked();
    pure callback load-image(string) -> image;
    callback remove-game(int);
    callback edit-game(int);
    callback launch-game(int);

    // settings callbacks
    callback choose-proton-path();
    callback choose-umu-path();
    callback click-save-settings();
    callback back-clicked();

    // add-game callbacks
    callback choose-cover-path();
    callback choose-exe-path();
    callback choose-wineprefix();
    callback click-save-game();
    callback cover-path-edited();
    callback exe-path-edited();
    callback wineprefix-edited();

    // preferred-width: 800px;
    // preferred-height: 600px;
    title: "Quarkpad";

    if current_page == 0: HomePage {
        games: games;
        load-image(path) => {
            load-image(path)
        }
        remove-game(index) => {
            remove-game(index)
        }
        edit-game(index) => {
            edit-game(index)
        }
        launch-game(index) => {
            launch-game(index)
        }
        settings-clicked => {
            settings-clicked()
        }
        add-fab-clicked => {
            add-fab-clicked()
        }
    }

    if current_page == 1: SettingsPage {
        settings: settings;
        choose-proton-path => {
            choose-proton-path()
        }
        choose-umu-path => {
            choose-umu-path()
        }
        click-save => {
            click-save-settings()
        }
        back-clicked => {
            back-clicked()
        }
    }

    if current_page == 2: AddGamePage {
        back-clicked => {
            back-clicked()
        }
        game: game;
        choose-cover-path => {
            choose-cover-path()
        }
        choose-exe-path => {
            choose-exe-path()
        }
        choose-wineprefix => {
            choose-wineprefix()
        }
        click-save => {
            click-save-game()
        }
        name-edited(text) => {
            game.name = text
        }
        cover-path-edited(text) => {
            game.cover-path = text
        }
        exe-path-edited(text) => {
            game.exe-path = text
        }
        wineprefix-edited(text) => {
            game.wineprefix = text
        }
    }
}
